name: Scheduled Weather Data Fetch

on:
  schedule:
    - cron: "*/10 * * * *" # 每 10 分鐘執行一次
  workflow_dispatch: # 允許手動觸發

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master # 確保在 main 分支上操作
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch weather data
        run: |
          echo "Starting weather data fetch..."
          node fetch-weather-data.js
          echo "Weather data fetch completed."
          echo "Checking generated file:"
          ls -l weather_data.json
          cat weather_data.json
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

      - name: Commit and push weather data
        run: |
          echo "Configuring git..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Adding weather_data.json..."
          git add weather_data.json

          echo "Checking git status..."
          git status

          echo "Committing changes..."
          # 如果沒有變更 (例如 API 資料與上次相同)，commit 會失敗，所以用 || true 忽略錯誤
          git commit -m "chore: 更新天氣資料" || echo "No changes to commit or commit failed, proceeding."

          echo "Force pushing changes to main..."
          git push -f origin HEAD:main # 強制推送以覆蓋遠端
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
